name: Publish Python Package

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+**"]

concurrency:
  group: packages
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: "**/pyproject.toml"

      - name: Build
        run: make build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        name: Release
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{ github.ref_name }}",
              name: "${{ github.ref_name }}",
              generate_release_notes: true
            })
